- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: variables/vpc-setup-variables

    - name: Creating "{{vpc_name}}" VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: Create public subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: true
        tags:
          Name: public-subnet-1
      register: pubsub1

    - debug:
        var: pubsub1

    - name: Create public subnet 2 in zone2
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: true
        tags:
          Name: public-subnet-2
      register: pubsub2

    - debug:
        var: pubsub2

    - name: Create public subnet 3 in zone3
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: true
        tags:
          Name: public-subnet-3
      register: pubsub3

    - debug:
        var: pubsub3

    - name: Create private subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PvtSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: false
        tags:
          Name: private-subnet-1
      register: pvtsub1

    - debug:
        var: pvtsub1

    - name: Create private subnet 2 in zone2
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PvtSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: false
        tags:
          Name: private-subnet-2
      register: pvtsub2

    - debug:
        var: pvtsub2

    - name: Create private subnet 3 in zone3
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PvtSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: false
        tags:
          Name: private-subnet-3
      register: pvtsub3

    - debug:
        var: pvtsub3

    - name: Setup internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
          Name: Internet gateway for my VPC
      register: vpcigw

    - debug:
        var: vpcigw

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
          Name: Public route table
        subnets:
          - "{{pubsub1.subnet.id}}"
          - "{{pubsub2.subnet.id}}"
          - "{{pubsub3.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: {{vpcigw.gateway_id}}
      register: public_route_table

    - debug:
        var: public_route_table