- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: variables/vpc-setup-variables

    - name: Creating "{{vpc_name}}" VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: Create public subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        az: "{{zone1}}"
        map_public: true
        tags:
          Name: public-subnet-1
      register: pubsub1

    - debug:
        var: pubsub1

    - name: Create public subnet 2 in zone2
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        az: "{{zone2}}"
        map_public: true
        tags:
          Name: public-subnet-2
      register: pubsub2

    - debug:
        var: pubsub2

    - name: Create public subnet 3 in zone3
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        az: "{{zone3}}"
        map_public: true
        tags:
          Name: public-subnet-3
      register: pubsub3

    - debug:
        var: pubsub3
