---
- name: Install & Setup RabbitMQ with user
  hosts: rmqserver
  gather_facts: no
  tasks:
    - name: Install prerequisites
      apt:
        name: apt-transport-https
        state: present

    - name: Install Erlang Repository Package
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb  # Updated version
      tags:
        - package

    - name: Add Erlang Solutions public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package

    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - package

    - name: Install Erlang
      apt:
        name: erlang
        state: present
      tags:
        - package

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present
      tags:
        - package

    - name: Add RabbitMQ official repository
      apt_repository:
        repo: 'deb https://dl.bintray.com/rabbitmq/debian bionic main'
        state: present
      tags:
        - package

    - name: Install Rabbit MQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package


    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf


    - rabbitmq_user:
        user: test #rabbitmq_user module to add rabbit mq user and password
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf


    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted